apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticas-container
      image: aluracursos/sistema-noticias:1
      ports:  
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-config
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      
