apiVersion: v1
kind: Pod
metadata:
  name: teste
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

    - name: jenkins-container
      image: jenkins/jenkins:lts
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"      
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: my-first-volume
  volumes:
    - name: my-first-volume
      persistentVolumeClaim:
        claimName: meu-pvc
      
