name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kind
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.17.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          pwd
          cd k8s
          ls
          kubectl apply -k .
          kubectl exec -it teste jenkins-container -- bash
          ls 
        
